### ISSUE TITLE
Need to parameterize these references

### ISSUE THREAD

**Issue by darynwhite** [NOAA-PMEL/GTMBA-AtlasProcessingScripts#4]
https://github.com/NOAA-PMEL/GTMBA-AtlasProcessingScripts/blob/fc90da4a6bf7cced1353b2d4048998978af07266/RAMdbload_toFile.pl#L208

https://github.com/NOAA-PMEL/GTMBA-AtlasProcessingScripts/blob/fc90da4a6bf7cced1353b2d4048998978af07266/RAMdbload_toFile.pl#L99

@curranfey I would like to parameterize these references. They seem to be the only real security concern in these files, and I don't immediately know how to do this in Perl.

**Comment by curranfey** [comment]
How about an environment variable? The code below uses system independent path construction. It also assumes that RAMDBLOADLOGDIR="" is an error.

```
use strict;
use warnings;
use Data::Dumper;
use File::Spec;

# A bash example:
#
#  export RAMDBLOADLOGDIR="/Users/white/Repos/AtlasData/Processing"
#

my $ram_dir = "pm123";
my $ramdbloadlog;

if (not defined $ENV{RAMDBLOADLOGDIR}) {
    die "ERROR: Environment variable missing, 'RAMDBLOADLOGDIR'";
}
if (not $ENV{RAMDBLOADLOGDIR}) {
    die "ERROR: Environment variable empty, 'RAMDBLOADLOGDIR'";
}
$ramdbloadlog = File::Spec->join($ENV{RAMDBLOADLOGDIR}, "RAMdbload_out.txt");
$ram_dir = File::Spec->join($ENV{RAMDBLOADLOGDIR}, $ram_dir);

print Dumper({ramdbloadlog=>$ramdbloadlog, ram_dir=>$ram_dir});
```
